
export const USER_ACTIONS ={
    CREATE_BILL:'CREATE_BILL',
    CREATE_PURCHASE:'CREATE_PURCHASE',
    FETCH_ALL_ITEMS :'FETCH_ALL_ITEMS',
    FETCH_ALL_CONFIGS :'FETCH_ALL_CONFIGS',
    FETCH_BILL_BY_ID :'FETCH_BILL_BY_ID',
    SEARCH_BILL : 'SEARCH_BILL',

    FETCH_LOGIN:'FETCH_LOGIN',
    CREATE_LOGIN:'CREATE_LOGIN',

    FETCH_DAILY_SALE_PURCHASE : 'FETCH_DAILY_SALE_PURCHASE'
}

export const REDUX_ACTIONS ={
    FETCH_ALL_ITEMS :'FETCH_ALL_ITEMS',
    FETCH_ALL_CONFIGS :'FETCH_ALL_CONFIGS',
    FETCH_BILL_BY_ID :'FETCH_BILL_BY_ID',
    PRINT_BILL :'PRINT_BILL',

    BILL_MODAL:'BILL_MODAL',
    SEARCH_BILL : 'SEARCH_BILL',
    FETCH_LOGIN:'FETCH_LOGIN',

    FETCH_DAILY_SALE_PURCHASE : 'FETCH_DAILY_SALE_PURCHASE'
}